#ifndef __DIRENT_H__
#define __DIRENT_H__

#include "types.h"

struct dirent
{
    ino_t       inode;       // inode referred
    uint8_t     name_size;    // size of the name
    char        name[];         // name of the referred inode
};

/* if inode is FS_INO_NULL, then the dirent is a memory leak */
/* Warning: dirent leaks are generated by rm or rmdir operations */
/* Filesystem must be periodically checked and cleaned */

#endif  // __DIRENT_H__
